package link.socket.kore.model.capability

import kotlinx.coroutines.CoroutineScope
import kotlinx.serialization.json.*
import link.socket.kore.data.ConversationRepository
import link.socket.kore.model.agent.KoreAgent
import link.socket.kore.model.agent.bundled.agentArgsList
import link.socket.kore.model.agent.bundled.agentNameList
import link.socket.kore.model.agent.bundled.getAgentDefinition
import link.socket.kore.model.tool.FunctionProvider
import link.socket.kore.model.tool.ParameterDefinition

/**
 * Represents a capability that an agent can possess.
 */
sealed interface AgentCapability : Capability {

    /**
     * Capability to get a list of available LLM agents.
     */
    data object GetAgents : AgentCapability {

        override val impl: Pair<String, FunctionProvider> =
            FunctionProvider.provide(
                name = "getAgents",
                description = "Returns a list of available LLM Agents.",
                function = GetAgents::getAgents,
            )

        /**
         * Returns a comma-separated list of agent names.
         */
        private fun getAgents(): String = agentNameList.joinToString(", ")
    }

    /**
     * Capability to get a list of available LLM agents along with their respective arguments.
     */
    data object GetAgentArgs : AgentCapability {

        override val impl: Pair<String, FunctionProvider> =
            FunctionProvider.provide(
                name = "getAgentArgs",
                description = "Returns a list of available LLM Agents, along with their respective arguments.",
                function = GetAgentArgs::getAgentArgs,
            )

        /**
         * Returns a newline-separated list of agent arguments.
         */
        private fun getAgentArgs(): String = agentArgsList.joinToString("\n\n")
    }

    /**
     * Capability to prompt another agent for completion based on given inputs.
     *
     * @property conversationRepository Repository to manage conversation data.
     * @property scope Coroutine scope for managing asynchronous operations.
     */
    data class PromptAgent(
        val conversationRepository: ConversationRepository,
        val scope: CoroutineScope,
    ) : AgentCapability {

        override val impl: Pair<String, FunctionProvider> =
            FunctionProvider.provideSuspend(
                name = "promptAgent",
                description = """
                    Requests a completion from another Agent with the given prompt and an example user's response to the LLM's initial Chat.
                    Returns the Chat completion generated by the sub-Agent.
                """.trimIndent(),
                function = { args: JsonObject ->
                    val agent = args.getOrElse("agent") {
                        JsonPrimitive("")
                    }.jsonPrimitive.content
                    val prompt = args.getValue("prompt").jsonPrimitive.content
                    val initialUserResponse = args.getOrElse("response") {
                        JsonPrimitive("")
                    }.jsonPrimitive.content

                    promptAgent(scope, agent, prompt, initialUserResponse)
                },
                parameterList = listOf(
                    ParameterDefinition(
                        name = "agent",
                        isRequired = false,
                        definition = buildJsonObject {
                            put("type", "string")
                            put("description", "The name of the LLM Agent that should be completing the prompt.")
                        }
                    ),
                    ParameterDefinition(
                        name = "prompt",
                        isRequired = true,
                        definition = buildJsonObject {
                            put("type", "string")
                            put("description", "The system instructions to use in case an Agent is not specified.")
                        }
                    ),
                    ParameterDefinition(
                        name = "response",
                        isRequired = false,
                        definition = buildJsonObject {
                            put("type", "string")
                            put("description", "An example of a user's response to what the initial Agent response would be.")
                        }
                    )
                )
            )

        /**
         * Requests a completion from another Agent.
         *
         * @param scope Coroutine scope for managing asynchronous operations.
         * @param agentName Optional name of the LLM Agent.
         * @param prompt The system instructions to use.
         * @param userResponse Optional example of a user's response.
         * @return The Chat completion generated by the sub-Agent.
         */
        private suspend fun promptAgent(
            scope: CoroutineScope,
            agentName: String?,
            prompt: String,
            userResponse: String?,
        ): String {
            val agent = KoreAgent(
                scope,
                agentName.getAgentDefinition(prompt),
                conversationRepository,
            )

            val conversationId = conversationRepository.createConversation(agent, null)

            if (userResponse != null) {
                // Option to get the _second_ LLM response, after a User provides their initial reply to the _first_ LLM response
                conversationRepository.runConversation(conversationId)
                conversationRepository.addUserChat(
                    conversationId = conversationId,
                    input = userResponse,
                )
            }

            conversationRepository.runConversation(conversationId)

            return conversationRepository
                .getValue(conversationId)
                ?.conversationHistory
                ?.getChats()
                ?.lastOrNull()
                ?.chatMessage
                ?.content ?: ""
        }
    }
}
